#!/bin/bash

#set -x
######################################################
# Run a castep job on a remote host using qsub
# by Martin Uhrin
#
# This script takes four parameters as shown below.
#
# Once running the script will submit the job to the
# remote host and poll it for competion periodically
#
# Usage: qsub_remote  [remote_host] [remote_dir] [job_file] [list of input files]
#
log_file=false
while getopts l: opt
do
  case "$opt" in
    l) log_file=$OPTARG ;;
   esac
done
shift `expr $OPTIND - 1`

if [ "$#" -lt 3 ]
then
  echo "Usage: qsub_remote  [remote_host] [remote_dir] [job_file] [list of input files]"
  exit 1
fi 

declare -r REMOTE_HOST=$1
declare -r REMOTE_DIR=$2
declare -r JOB_FILE=$3
shift 3
declare -ar INPUT_FILES=("$@")

# Interval between checking if job is finished (in seconds)
declare -r JOB_POLL_INTERVAL=60

declare -r RAND_FOLDER=`strings /dev/urandom | tr -dc [:alnum:] | head -c8`
declare -r WORK_DIR=$REMOTE_DIR/$RAND_FOLDER

#############################
## Functions 

function log
{
  if [ -n "$log_file" ]
  then
    echo [`date +"%D %T"`] qsub_remote: $1 >> $log_file
  fi
}

if [ -z "$JOB_FILE" -o ! -f "$JOB_FILE" ]
then
  exit 1
fi

# Make the remote directory and copy over the work files
ssh $REMOTE_HOST mkdir -p $WORK_DIR
scp ${INPUT_FILES[@]} $JOB_FILE $REMOTE_HOST:$WORK_DIR

log "Starting job $JOB_FILE in $REMOTE_HOST:$WORK_DIR"
JOBID=`ssh $REMOTE_HOST "cd $WORK_DIR; qsub $JOB_FILE"`
# Exit if qsub failed or the job id is empty
if [ "$?" -ne "0" -o -z "$JOBID" ]
then
  exit 1
fi
   
# Loop until the job finishes
finished=false
while ! $finished
do
  sleep $JOB_POLL_INTERVAL

  ssh $REMOTE_HOST qstat $JOBID > /dev/null 2>&1
  result=$?
  if [ "$result" -ne "0" -a "$result" -ne "255" ] # 255 means ssh couldn't reach host, keepy trying
  then
    log "Job $JOB_FILE finished successfully, exit status: $result"
    finished=true
  fi
done

# Copy everything back over
scp $REMOTE_HOST:$WORK_DIR/\* .
if [ "$?" -eq "0" ]
then
  log "Copied job files for $JOB_FILE back successfully." 
  # Delete the remote working directory
  ssh $REMOTE_HOST "if [ -d \"$WORK_DIR\" ]; then rm -r $WORK_DIR; fi"
fi


