#!/bin/bash --login
#PBS -N structure_predict
#PBS -V
#PBS -l mppwidth=32
#PBS -l mppnppn=32
#PBS -l walltime=00:10:00
#PBS -A n03-lv-users

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR

## LOAD MODULES #############

# Load the CASTEP module
module swap PrgEnv-cray PrgEnv-gnu
module add castep
module add boost
module add acml

# This line sets the temporary directory - without it CASTEP will fail
export GFORTRAN_TMPDIR=$PBS_O_WORKDIR

# Set the number of threads to 1
# This prevents any system libraries from automatically
# using threading.
export OMP_NUM_THREADS=1

export NPROC=`qstat -f $PBS_JOBID | grep mppwidth | awk '{print $3}'`
export NTASK=`qstat -f $PBS_JOBID | grep mppnppn  | awk '{print $3}'`

#==USER SETTINGS==
STOOLS_BIN=~/work/bin/stools/bin
SSEARCH_INPUT="P.ssearch"

# Change the name of the input file to match your own job
$STOOLS_BIN/ssearch -D "castepExe=aprun -n $NPROC -N $NTASK castep" $SSEARCH_INPUT

