#!/bin/bash

# Debugging
#set -x

declare -r usage="Usage: $0 [-np n] [command]"

if [ $# -lt 1 ]; then
  echo $usage
  exit 1
fi

np=1

while [ $# -gt 1 ] ; do
  case $1 in
    -np) np=$2 ; shift 2 ; break; ;; 
  esac
done
command=$1
shift 1;
args=$*

# Run the thing
$command -D "nProcs=$np" $args
